version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "jest",
    "browser"
  ]
  plugins = ["angular"]
  style_guide = "standard"
  dialect = "typescript"
